# The URL the site will be built for
title = "Alberto Trigo"
base_url = "https://albertotrigo.eu"
theme = "no-style-please"
description = "My personal website"
default_language = "en"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feed = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


taxonomies = [
    { name = "tags" },
]

[markdown]
highlight_code = true
smart_punctuation = true
highlight_theme = "ayu-dark"

[extra]
add_toc = true
#list_pages = true
author = "Alberto Trigo"
header_nav = [
    { name = "~home", url = "/" },
    { name = "&posts", url = "/blog" },
    { name = "#tags", url = "/tags" },
]
footer_nav = [

]
